feat(presets): add 'daynight' preset
rafaelrinaldi/loading-indicator pull request #3
Opened 2017-10-25 03:00 UTC by marcoscaceres

2017-10-25 14:12 UTC, rafaelrinaldi requested changes
Thank you for the PR. Just added one note. Also, can you check why the build is failing? Please, make sure tests are passing.

2017-10-25 14:12 UTC, rafaelrinaldi commented on presets.js
> +    '\uD83C\uDF15', // 🌕
No need to add the comments here 👍

2017-10-27 05:32 UTC, marcoscaceres commented
Just wondering, how come you don't include the emojis directly in the code? Is there known compat issues?

2017-10-30 09:42 UTC, marcoscaceres commented
Not sure why the semaphoreci thing is failing. Any ideas?

2017-10-30 19:15 UTC, rafaelrinaldi commented
@marcoscaceres Alright, I will take a look as soon as I can.

2018-03-07 05:21 UTC, marcoscaceres commented
Friendly ping :)

2019-07-23 05:30 UTC, marcoscaceres commented
Closing due to inactivity.

2019-07-23 05:30 UTC, closed without merging

2019-08-08 14:14 UTC, rafaelrinaldi commented
@marcoscaceres I haven't been active on GitHub much lately since I'm very busy on my full time job. I hope you understand.

I've added this to my todo list to check on the weekend. I want to avoid merging it with CI failing, so I'll figure out why it's breaking and then introduce your changes on top of it. Will `@` you on the PR.

2019-08-20 05:24 UTC, marcoscaceres commented
@rafaelrinaldi totally understand. It's no problem. I added these mostly as a fun thing - but no stress if they don't get merged.